/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.solo_noble_game.ŞamilBilalÖZAYDIN_1921221011_SoloNoble_DataStructure;

/**
 *
 * @author Bilal
 */
public class Main extends javax.swing.JFrame {

    MainGame mainGame;
    
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tema = new javax.swing.JPanel();
        pnl_labelBckgrnd = new javax.swing.JPanel();
        lbl_warning = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        cmbx_amount = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnl_tema.setBackground(new java.awt.Color(0, 153, 51));

        pnl_labelBckgrnd.setBackground(new java.awt.Color(153, 102, 0));
        pnl_labelBckgrnd.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3), null));

        lbl_warning.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_warning.setText("An even number must be entered to create a (nxn) table:");

        javax.swing.GroupLayout pnl_labelBckgrndLayout = new javax.swing.GroupLayout(pnl_labelBckgrnd);
        pnl_labelBckgrnd.setLayout(pnl_labelBckgrndLayout);
        pnl_labelBckgrndLayout.setHorizontalGroup(
            pnl_labelBckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_labelBckgrndLayout.createSequentialGroup()
                .addComponent(lbl_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        pnl_labelBckgrndLayout.setVerticalGroup(
            pnl_labelBckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_labelBckgrndLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_warning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        cmbx_amount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbx_amount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "8", "10", "12", "14", "16", "18", "20" }));

        javax.swing.GroupLayout pnl_temaLayout = new javax.swing.GroupLayout(pnl_tema);
        pnl_tema.setLayout(pnl_temaLayout);
        pnl_temaLayout.setHorizontalGroup(
            pnl_temaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_temaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnl_temaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_temaLayout.createSequentialGroup()
                        .addComponent(cmbx_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_labelBckgrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnl_temaLayout.setVerticalGroup(
            pnl_temaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_temaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(pnl_labelBckgrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_temaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmbx_amount))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_tema);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed

        String input = cmbx_amount.getItemAt(cmbx_amount.getSelectedIndex());
        int parseInput;
        parseInput = Integer.valueOf(input);
        mainGame = new MainGame(parseInput);
        mainGame.setBeginFrame(this);
        this.setVisible(false);
        mainGame.setVisible(true);
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JComboBox<String> cmbx_amount;
    private javax.swing.JLabel lbl_warning;
    private javax.swing.JPanel pnl_labelBckgrnd;
    private javax.swing.JPanel pnl_tema;
    // End of variables declaration//GEN-END:variables
}
